polls_site/polls/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:subject_id>/', views.vote, name='vote'),
    path('<int:subject_id>/recieve_vote/', views.recieve_vote, name='recieve_vote'),
    path('results/', views.results, name='results'),
]

polls_site/polls_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls_site/polls/models.py
from django.db import models

class Teacher(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Subject(models.Model):
    name = models.CharField(max_length=200)
    plot_image = models.ImageField

    def __str__(self):
        return self.name

class Choice(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    
    total_voters_number = models.IntegerField(default=0)
    total_quality = models.IntegerField(default=0)
    total_friendliness = models.IntegerField(default=0)
    total_motivation = models.IntegerField(default=0)
    total_ease = models.IntegerField(default=0)

    class Meta:
        unique_together = ('teacher', 'subject')

    def get_score(self, attr: str):
        if attr == 'total_general':
            return (self.get_score('total_quality') + self.get_score('total_friendliness') + self.get_score('total_motivation') +self.get_score('total_ease'))/4
        else:
            if self.total_voters_number > 0:
                return self.__getattribute__(attr)/self.total_voters_number
            else:
                return 0

    def __str__(self):
        return f"T: {str(self.teacher)}, S: {str(self.subject)}"
            

polls_site/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.cache import never_cache

from .models import Subject, Choice
from .utils.plotting import create_plot


def index(request):
    return render(request, 'polls/index.html')

def vote(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    return render(request, 'polls/vote.html', {
        'subject': subject, 
        'range': range(1,11)})

def recieve_vote(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    try:
        context = request.POST
        selected_choice = subject.choice_set.get(teacher_id=int(context['teachers']))
        selected_choice.total_quality += int(context['quality_score'])
        selected_choice.total_friendliness += int(context['friendliness_score'])
        selected_choice.total_motivation += int(context['motivation_score'])
        selected_choice.total_ease += int(context['ease_score'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/vote.html', {
            'subject': subject,
            'range': range(1,11),
            'error_message': "Opcje nie zostały poprawnie zaznaczone",
        })
    else:
        selected_choice.total_voters_number += 1
        selected_choice.save()

        # update plot
        create_plot(subject)

        remaining_subjects = Subject.objects.filter(pk__gt=int(subject_id)).order_by('id').all()

        if remaining_subjects:
            return HttpResponseRedirect(reverse('polls:vote', args=(remaining_subjects[0].id,)))
        else:
            return HttpResponseRedirect(reverse('polls:results'))

@never_cache  # to prevent caching chart images, probably not the best solution
def results(request):
    return render(request, 'polls/results.html', {'subjects': Subject.objects.all()})

polls_site/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome Page</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style_index.css' %}">
</head>
<body>
    <div class="link_btn">
        <a href="{% url 'polls:vote' 1 %}">Głosuj</a>
    </div>
    <div class="link_btn">
    <a href="{% url 'polls:results' %}">Wyniki</a>
    </div>
</body>
</html>

polls_site/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style_results.css' %}">
</head>
<body>
    <div class="header">
        <h2>Wyniki</h2>
    </div>
    {% for subject in subjects %}
    <div class="chart">
        <img src="../../static/polls/images/{{ subject.id }}_plot.png" alt="{{ subject.id }}_plot.png">
    </div>
    {% endfor %}
</body>
</html>

polls_site/polls/templates/polls/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote - {{ subject.name }}</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style_vote.css' %}">
</head>
<body>
    <div class="header">
        <h2>Przedmiot: {{ subject.name }}</h2>
    </div>
    <div class="bottom_div">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="{% url 'polls:recieve_vote' subject.id %}" method="post" class="input_field">
        {% csrf_token %}
        <fieldset class="field_set">
            <div class="options">
                <h3>Wybierz prowadzącego:</h3>
                <div>
                    <select name="teachers" id="teachers">
                        {% for choice in subject.choice_set.all %}
                            <option value="{{ choice.teacher.id }}">{{ choice.teacher }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="options">
                <h4>Jakość nauczania: </h4>
                <div class="radio">
                    {% for score in range %}
                        <input type="radio" name="quality_score" id="quality_score{{ score }}" value="{{ score }}">
                        <label for="quality_score{{ score }}">{{ score }}</label>
                    {% endfor %}
                </div>
            </div>
            <div class="options">
                <h4>Przyjazne podejście: </h4>
                <div class="radio">
                    {% for score in range %}
                        <input type="radio" name="friendliness_score" id="friendliness_score{{ score }}" value="{{ score }}">
                        <label for="friendliness_score{{ score }}">{{ score }}</label>
                    {% endfor %}
                </div>
            </div>
            <div class="options">
                <h4>Motywowanie do nauki: </h4>
                <div class="radio">
                    {% for score in range %}
                        <input type="radio" name="motivation_score" id="motivation_score{{ score }}" value="{{ score }}">
                        <label for="motivation_score{{ score }}">{{ score }}</label>
                    {% endfor %}
                </div>
            </div>
            <div class="options">
                <h4>Łatwość zdania (więcej = łatwiej): </h4>
                <div class="radio">
                    {% for score in range %}
                        <input type="radio" name="ease_score" id="ease_score{{ score }}" value="{{ score }}">
                        <label for="ease_score{{ score }}">{{ score }}</label>
                    {% endfor %}
                </div>
            </div>
            <div class="btn">
                <input type="submit" value="Zagłosuj i przejdź dalej">
            </div>
        </fieldset>
        </form>
    </div>
</body>
</html>